# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title       : TEDxSunwayUniversity - Ideas Worth Spreading
owner       : TEDxSunwayUniversity
description : The official website for TEDxSunwayUniversity
baseurl     : ""
url         : "https://potateros.github.io"
email       : admin@tedxsunwayuniversity.com
twitter     : TEDxSunwayUni
instagram   : tedxsunwayuniversity
facebook    : TEDxSunwayUniversity
location    : https://goo.gl/maps/jj69WVgNcdn

logo        : "/images/tedxsu-logo-main.png"

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
